include:
  - path: redis.yaml
  - path:
      - ../opik/deployment/docker-compose/docker-compose.yaml
      - ../opik/deployment/docker-compose/docker-compose.override.yaml

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:

configs:
  qdrant_config:
    content: |
      log_level: INFO
