FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_NO_CACHE_DIR=on \
    PYTHONPATH=/app/src

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates build-essential python3-dev\
    && rm -rf /var/lib/apt/lists/*

RUN pip install streamlit requests python-dotenv opik

COPY src/chat ./chat

EXPOSE 8501

CMD ["streamlit", "run", "chat/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
