services:
  redis-general:
    image: redis:latest
    container_name: redis-general
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "PING"]
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  redis_data:
